using System;
using System.IO;
using System.Runtime.Serialization.Json;
using System.Text;

public class ReturnBalances
{
	public static ReturnBalances Create(string json)
	{
		ReturnBalances deserializedUser = new ReturnBalances();
		MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes(json));
		DataContractJsonSerializer ser = new DataContractJsonSerializer(deserializedUser.GetType());
		deserializedUser = ser.ReadObject(ms) as ReturnBalances;
		ms.Close();
		return deserializedUser;
	}
	
	public string ABY { get; set; }
    public string AC { get; set; }
    public string ACH { get; set; }
    public string ADN { get; set; }
    public string AEON { get; set; }
    public string AERO { get; set; }
    public string AIR { get; set; }
    public string AMP { get; set; }
    public string APH { get; set; }
    public string ARCH { get; set; }
    public string ARDR { get; set; }
    public string AUR { get; set; }
    public string AXIS { get; set; }
    public string BALLS { get; set; }
    public string BANK { get; set; }
    public string BBL { get; set; }
    public string BBR { get; set; }
    public string BCC { get; set; }
    public string BCN { get; set; }
    public string BCY { get; set; }
    public string BDC { get; set; }
    public string BDG { get; set; }
    public string BELA { get; set; }
    public string BITCNY { get; set; }
    public string BITS { get; set; }
    public string BITUSD { get; set; }
    public string BLK { get; set; }
    public string BLOCK { get; set; }
    public string BLU { get; set; }
    public string BNS { get; set; }
    public string BONES { get; set; }
    public string BOST { get; set; }
    public string BTC { get; set; }
    public string BTCD { get; set; }
    public string BTCS { get; set; }
    public string BTM { get; set; }
    public string BTS { get; set; }
    public string BURN { get; set; }
    public string BURST { get; set; }
    public string C2 { get; set; }
    public string CACH { get; set; }
    public string CAI { get; set; }
    public string CC { get; set; }
    public string CCN { get; set; }
    public string CGA { get; set; }
    public string CHA { get; set; }
    public string CINNI { get; set; }
    public string CLAM { get; set; }
    public string CNL { get; set; }
    public string CNMT { get; set; }
    public string CNOTE { get; set; }
    public string COMM { get; set; }
    public string CON { get; set; }
    public string CORG { get; set; }
    public string CRYPT { get; set; }
    public string CURE { get; set; }
    public string CYC { get; set; }
    public string DAO { get; set; }
    public string DASH { get; set; }
    public string DCR { get; set; }
    public string DGB { get; set; }
    public string DICE { get; set; }
    public string DIEM { get; set; }
    public string DIME { get; set; }
    public string DIS { get; set; }
    public string DNS { get; set; }
    public string DOGE { get; set; }
    public string DRKC { get; set; }
    public string DRM { get; set; }
    public string DSH { get; set; }
    public string DVK { get; set; }
    public string EAC { get; set; }
    public string EBT { get; set; }
    public string ECC { get; set; }
    public string EFL { get; set; }
    public string EMC2 { get; set; }
    public string EMO { get; set; }
    public string ENC { get; set; }
    public string ETC { get; set; }
    public string ETH { get; set; }
    public string eTOK { get; set; }
    public string EXE { get; set; }
    public string EXP { get; set; }
    public string FAC { get; set; }
    public string FCN { get; set; }
    public string FCT { get; set; }
    public string FIBRE { get; set; }
    public string FLAP { get; set; }
    public string FLDC { get; set; }
    public string FLO { get; set; }
    public string FLT { get; set; }
    public string FOX { get; set; }
    public string FRAC { get; set; }
    public string FRK { get; set; }
    public string FRQ { get; set; }
    public string FVZ { get; set; }
    public string FZ { get; set; }
    public string FZN { get; set; }
    public string GAME { get; set; }
    public string GAP { get; set; }
    public string GDN { get; set; }
    public string GEMZ { get; set; }
    public string GEO { get; set; }
    public string GIAR { get; set; }
    public string GLB { get; set; }
    public string GML { get; set; }
    public string GNO { get; set; }
    public string GNS { get; set; }
    public string GNT { get; set; }
    public string GOLD { get; set; }
    public string GPC { get; set; }
    public string GPUC { get; set; }
    public string GRC { get; set; }
    public string GRCX { get; set; }
    public string GRS { get; set; }
    public string GUE { get; set; }
    public string H2O { get; set; }
    public string HIRO { get; set; }
    public string HOT { get; set; }
    public string HUC { get; set; }
    public string HUGE { get; set; }
    public string HVC { get; set; }
    public string HYP { get; set; }
    public string HZ { get; set; }
    public string IFC { get; set; }
    public string INDEX { get; set; }
    public string IOC { get; set; }
    public string ITC { get; set; }
    public string IXC { get; set; }
    public string JLH { get; set; }
    public string JPC { get; set; }
    public string JUG { get; set; }
    public string KDC { get; set; }
    public string KEY { get; set; }
    public string LBC { get; set; }
    public string LC { get; set; }
    public string LCL { get; set; }
    public string LEAF { get; set; }
    public string LGC { get; set; }
    public string LOL { get; set; }
    public string LOVE { get; set; }
    public string LQD { get; set; }
    public string LSK { get; set; }
    public string LTBC { get; set; }
    public string LTC { get; set; }
    public string LTCX { get; set; }
    public string MAID { get; set; }
    public string MAST { get; set; }
    public string MAX { get; set; }
    public string MCN { get; set; }
    public string MEC { get; set; }
    public string METH { get; set; }
    public string MIL { get; set; }
    public string MIN { get; set; }
    public string MINT { get; set; }
    public string MMC { get; set; }
    public string MMNXT { get; set; }
    public string MMXIV { get; set; }
    public string MNTA { get; set; }
    public string MON { get; set; }
    public string MRC { get; set; }
    public string MRS { get; set; }
    public string MTS { get; set; }
    public string MUN { get; set; }
    public string MYR { get; set; }
    public string MZC { get; set; }
    public string N5X { get; set; }
    public string NAS { get; set; }
    public string NAUT { get; set; }
    public string NAV { get; set; }
    public string NBT { get; set; }
    public string NEOS { get; set; }
    public string NL { get; set; }
    public string NMC { get; set; }
    public string NOBL { get; set; }
    public string NOTE { get; set; }
    public string NOXT { get; set; }
    public string NRS { get; set; }
    public string NSR { get; set; }
    public string NTX { get; set; }
    public string NXC { get; set; }
    public string NXT { get; set; }
    public string NXTI { get; set; }
    public string OMNI { get; set; }
    public string OPAL { get; set; }
    public string PAND { get; set; }
    public string PASC { get; set; }
    public string PAWN { get; set; }
    public string PIGGY { get; set; }
    public string PINK { get; set; }
    public string PLX { get; set; }
    public string PMC { get; set; }
    public string POT { get; set; }
    public string PPC { get; set; }
    public string PRC { get; set; }
    public string PRT { get; set; }
    public string PTS { get; set; }
    public string Q2C { get; set; }
    public string QBK { get; set; }
    public string QCN { get; set; }
    public string QORA { get; set; }
    public string QTL { get; set; }
    public string RADS { get; set; }
    public string RBY { get; set; }
    public string RDD { get; set; }
    public string REP { get; set; }
    public string RIC { get; set; }
    public string RZR { get; set; }
    public string SBD { get; set; }
    public string SC { get; set; }
    public string SDC { get; set; }
    public string SHIBE { get; set; }
    public string SHOPX { get; set; }
    public string SILK { get; set; }
    public string SJCX { get; set; }
    public string SLR { get; set; }
    public string SMC { get; set; }
    public string SOC { get; set; }
    public string SPA { get; set; }
    public string SQL { get; set; }
    public string SRCC { get; set; }
    public string SRG { get; set; }
    public string SSD { get; set; }
    public string STEEM { get; set; }
    public string STR { get; set; }
    public string STRAT { get; set; }
    public string SUM { get; set; }
    public string SUN { get; set; }
    public string SWARM { get; set; }
    public string SXC { get; set; }
    public string SYNC { get; set; }
    public string SYS { get; set; }
    public string TAC { get; set; }
    public string TOR { get; set; }
    public string TRUST { get; set; }
    public string TWE { get; set; }
    public string UIS { get; set; }
    public string ULTC { get; set; }
    public string UNITY { get; set; }
    public string URO { get; set; }
    public string USDE { get; set; }
    public string USDT { get; set; }
    public string UTC { get; set; }
    public string UTIL { get; set; }
    public string UVC { get; set; }
    public string VIA { get; set; }
    public string VOOT { get; set; }
    public string VOX { get; set; }
    public string VRC { get; set; }
    public string VTC { get; set; }
    public string WC { get; set; }
    public string WDC { get; set; }
    public string WIKI { get; set; }
    public string WOLF { get; set; }
    public string X13 { get; set; }
    public string XAI { get; set; }
    public string XAP { get; set; }
    public string XBC { get; set; }
    public string XC { get; set; }
    public string XCH { get; set; }
    public string XCN { get; set; }
    public string XCP { get; set; }
    public string XCR { get; set; }
    public string XDN { get; set; }
    public string XDP { get; set; }
    public string XEM { get; set; }
    public string XHC { get; set; }
    public string XLB { get; set; }
    public string XMG { get; set; }
    public string XMR { get; set; }
    public string XPB { get; set; }
    public string XPM { get; set; }
    public string XRP { get; set; }
    public string XSI { get; set; }
    public string XST { get; set; }
    public string XSV { get; set; }
    public string XUSD { get; set; }
    public string XVC { get; set; }
    public string XXC { get; set; }
    public string YACC { get; set; }
    public string YANG { get; set; }
    public string YC { get; set; }
    public string YIN { get; set; }
    public string ZEC { get; set; }
}